// packages/create/templates/starter-source/solid/src/components/ui/button/Button.tsx
import { styles } from './styles';

import type { JSX } from 'solid-js';

export interface ButtonProps {
  readonly children: JSX.Element;
  readonly onClick?: () => void;
  // A form's submit is the one that is not a plain button; everything else presses and does something now.
  readonly type?: 'button' | 'submit';
  readonly disabled?: boolean;
}

// `props` is read rather than destructured, or each value would be read once and never again.
export const Button = (props: ButtonProps): JSX.Element => {
  return (
    <button
      {...styles.button}
      type={props.type ?? 'button'}
      disabled={props.disabled ?? false}
      onClick={() => {
        props.onClick?.();
      }}
    >
      {props.children}
    </button>
  );
};

// packages/create/templates/starter-source/react/src/components/ui/button/Button.tsx
import { styles } from './styles';

import type { FC, ReactNode } from 'react';

export interface ButtonProps {
  readonly children: ReactNode;
  readonly onClick?: () => void;
  // A form's submit is the one that is not a plain button; everything else presses and does something now.
  readonly type?: 'button' | 'submit';
  readonly disabled?: boolean;
}

export const Button: FC<ButtonProps> = ({
  children,
  onClick,
  type = 'button',
  disabled = false,
}) => {
  return (
    <button
      {...styles.button}
      type={type}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  );
};
