// packages/create/templates/starter-source/solid/src/App.tsx
import {
  createSignal,
  type JSX,
  Show,
} from 'solid-js';

import { AppHeader } from './components/features/app-header/AppHeader';
import { NAME } from './config/linteljs';
import { ROUTES } from './pages/routes';

export interface AppProps {
  readonly initialPage?: string;
}

// `props` is read rather than destructured: destructuring reads `initialPage` once.
export const App = (props: AppProps): JSX.Element => {
  const [page, setPage] = createSignal(props.initialPage ?? ROUTES[0].id);
  const current = () => {
    return ROUTES
      .find((route) => {
        return route.id === page();
      });
  };

  return (
    <>
      <AppHeader
        name={NAME}
        current={page()}
        onNavigate={setPage}
      />
      {/* `keyed`: without it the block is built once and switching to another page re-renders the first one. */}
      <Show when={current()} keyed>
        {(route) => {
          return route.element();
        }}
      </Show>
    </>
  );
};

// packages/create/templates/starter-source/react/src/App.tsx
import { type FC, useState } from 'react';

import { AppHeader } from './components/features/app-header/AppHeader';
import { NAME } from './config/linteljs';
import { ROUTES } from './pages/routes';

export interface AppProps {
  readonly initialPage?: string;
}

export const App: FC<AppProps> = ({ initialPage = ROUTES[0].id }) => {
  const [page, setPage] = useState(initialPage);
  const current = ROUTES
    .find((route) => {
      return route.id === page;
    });

  return (
    <>
      <AppHeader
        name={NAME}
        current={page}
        onNavigate={setPage}
      />
      {current?.element}
    </>
  );
};
