// packages/create/templates/starter-source/nuxt/src/app.vue
<script setup lang="ts">
import { NAME } from '@config/linteljs';

import AppHeader from './components/features/app-header/AppHeader.vue';
</script>

<!-- `NuxtPage` and the header are Nuxt's global components, which is why neither is imported. -->
<template>
  <AppHeader :name="NAME" />
  <NuxtPage />
</template>

// packages/create/templates/starter-source/react/src/App.tsx
import { type FC, useState } from 'react';

import { AppHeader } from './components/features/app-header/AppHeader';
import { NAME } from './config/linteljs';
import { ROUTES } from './pages/routes';

export interface AppProps {
  readonly initialPage?: string;
}

export const App: FC<AppProps> = ({ initialPage = ROUTES[0].id }) => {
  const [page, setPage] = useState(initialPage);
  const current = ROUTES
    .find((route) => {
      return route.id === page;
    });

  return (
    <>
      <AppHeader
        name={NAME}
        current={page}
        onNavigate={setPage}
      />
      {current?.element}
    </>
  );
};
