// packages/create/templates/starter-source/react/i18n/src/pages/version/VersionPage.tsx
import { Trans, useTranslation } from 'react-i18next';

import { ANSWERS, STACK } from '../../config/linteljs';

import type { FC } from 'react';

// Recorded at birth: a browser cannot read its machine's Node or package manager.
export const VersionPage: FC = () => {
  const { t } = useTranslation();

  return (
    <main className="page">
      <h1 className="page-title">{t('version')}</h1>
      <p className="page-lede">{t('versionLede')}</p>

      <section className="section">
        <h2 className="section-title">{t('versionStack')}</h2>
        <dl className="rows">
          {STACK
            .map(({ name, version }) => {
              return (
                <div key={name} className="row">
                  <dt>{name}</dt>
                  <dd>{version}</dd>
                </div>
              );
            })}
        </dl>
      </section>

      <section className="section">
        <h2 className="section-title">{t('versionAnswers')}</h2>
        <dl className="rows">
          {ANSWERS
            .map(({ label, value }) => {
              return (
                <div key={label} className="row">
                  <dt>{label}</dt>
                  <dd>{value}</dd>
                </div>
              );
            })}
        </dl>
        <p className="note">
          <Trans
            i18nKey="versionRecorded"
            values={{
              file: 'linteljs.config.json',
              command: 'sync',
            }}
            components={{ code: <code /> }}
          />
        </p>
      </section>
    </main>
  );
};

// packages/create/templates/starter-source/solid/i18n/src/pages/version/VersionPage.tsx
import { For, type JSX } from 'solid-js';

import { CodeText } from '../../components/ui/code-text/CodeText';
import { ANSWERS, STACK } from '../../config/linteljs';
import { t } from '../../i18n';

// Recorded at birth: a browser cannot read its machine's Node or package manager.
export const VersionPage = (): JSX.Element => {
  return (
    <main class="page">
      <h1 class="page-title">{t('version')}</h1>
      <p class="page-lede">{t('versionLede')}</p>

      <section class="section">
        <h2 class="section-title">{t('versionStack')}</h2>
        <dl class="rows">
          <For each={STACK}>
            {(entry) => {
              return (
                <div class="row">
                  <dt>{entry.name}</dt>
                  <dd>{entry.version}</dd>
                </div>
              );
            }}
          </For>
        </dl>
      </section>

      <section class="section">
        <h2 class="section-title">{t('versionAnswers')}</h2>
        <dl class="rows">
          <For each={ANSWERS}>
            {(entry) => {
              return (
                <div class="row">
                  <dt>{entry.label}</dt>
                  <dd>{entry.value}</dd>
                </div>
              );
            }}
          </For>
        </dl>
        <p class="note">
          <CodeText
            text={t('versionRecorded', {
              file: 'linteljs.config.json',
              command: 'sync',
            })}
          />
        </p>
      </section>
    </main>
  );
};
