// packages/create/templates/starter-source/react/msw/src/pages/contact/ContactPage.tsx
import { CONTACT_TEXT, type Translate } from '@services/contact-form/contactFormService';

import { Button, TextInput } from '@ui';

import { useContactForm } from './use-contact-form/useContactForm';

import type { FC } from 'react';

const inEnglish: Translate = (key) => {
  return CONTACT_TEXT[key];
};

export const ContactPage: FC = () => {
  const {
    fields,
    sent,
    submitting,
    canSubmit,
    onSubmit,
  } = useContactForm(inEnglish);

  return (
    <main className="page">
      <h1 className="page-title">Contact</h1>
      <p className="page-lede">Two fields, validated on blur. It posts to /api/contact, mocked in dev.</p>

      {sent
        ? (
            <p className="sent" role="status">Thanks. Your message was sent.</p>
          )
        : (
            <form noValidate onSubmit={onSubmit}>
              <TextInput {...fields.email} />
              <TextInput {...fields.message} />
              <Button type="submit" disabled={!canSubmit || submitting}>Send</Button>
            </form>
          )}
    </main>
  );
};

// packages/create/templates/starter-source/solid/msw/src/pages/contact/ContactPage.tsx
import { CONTACT_TEXT, type Translate } from '@services/contact-form/contactFormService';

import { Button, TextInput } from '@ui';

import { createContactForm } from './create-contact-form/createContactForm';

import type { JSX } from 'solid-js';

const inEnglish: Translate = (key) => {
  return CONTACT_TEXT[key];
};

export const ContactPage = (): JSX.Element => {
  const form = createContactForm(inEnglish);

  return (
    <main class="page">
      <h1 class="page-title">Contact</h1>
      <p class="page-lede">Two fields, validated on blur. It posts to /api/contact, mocked in dev.</p>

      {form.sent()
        ? <p class="sent" role="status">Thanks. Your message was sent.</p>
        : (
            <form novalidate onSubmit={form.onSubmit}>
              <TextInput {...form.fields.email} />
              <TextInput {...form.fields.message} />
              <Button type="submit" disabled={!form.canSubmit()}>Send</Button>
            </form>
          )}
    </main>
  );
};
