// packages/create/templates/starter-source/svelte/src/components/ui/text-input/TextInput.svelte
<script lang="ts">
  import { styles } from './textInputStyles';

  import type { TextInputProps } from './types';

  const {
    id,
    label,
    value,
    onChange,
    onBlur,
    error,
    multiline = false,
    type = 'text',
  }: TextInputProps = $props();

  const describedBy = $derived(error === undefined ? undefined : `${id}-error`);
</script>

<!-- A dense tool pane can get away with `aria-label` alone; a form cannot. -->
<div {...styles.field}>
  <label {...styles.label} for={id}>{label}</label>
  {#if multiline}
    <textarea
      {id}
      {...styles.textarea(error !== undefined)}
      name={id}
      {value}
      aria-invalid={error !== undefined}
      aria-describedby={describedBy}
      onblur={onBlur}
      oninput={(event) => {
        onChange(event.currentTarget.value);
      }}
    ></textarea>
  {:else}
    <input
      {id}
      {...styles.input(error !== undefined)}
      name={id}
      {type}
      {value}
      aria-invalid={error !== undefined}
      aria-describedby={describedBy}
      onblur={onBlur}
      oninput={(event) => {
        onChange(event.currentTarget.value);
      }}
    />
  {/if}
  {#if error !== undefined}
    <p {...styles.error} id={`${id}-error`}>{error}</p>
  {/if}
</div>

// packages/create/templates/starter-source/react/src/components/ui/text-input/TextInput.tsx
import { styles } from './textInputStyles';

import type { FC } from 'react';

// Required and nullable: a getter cannot be conditionally present under `exactOptionalPropertyTypes`.
export interface TextInputProps {
  readonly id: string;
  readonly label: string;
  readonly value: string;
  readonly onChange: (value: string) => void;
  readonly onBlur?: () => void;
  readonly error: string | undefined;
  readonly multiline?: boolean;
  readonly type?: 'text' | 'email';
}

// A dense tool pane can get away with `aria-label` alone; a form cannot.
export const TextInput: FC<TextInputProps> = ({
  id,
  label,
  value,
  onChange,
  onBlur,
  error,
  multiline = false,
  type = 'text',
}) => {
  const invalid = error !== undefined;
  const shared = {
    'id': id,
    'name': id,
    value,
    'aria-invalid': invalid,
    'aria-describedby': invalid ? `${id}-error` : undefined,
    onBlur,
  };

  return (
    <div {...styles.field}>
      <label {...styles.label} htmlFor={id}>{label}</label>
      {multiline
        ? (
            <textarea
              {...shared}
              {...styles.textarea(invalid)}
              onChange={(event) => {
                onChange(event.target.value);
              }}
            />
          )
        : (
            <input
              {...shared}
              {...styles.input(invalid)}
              type={type}
              onChange={(event) => {
                onChange(event.target.value);
              }}
            />
          )}
      {invalid ? <p {...styles.error} id={`${id}-error`}>{error}</p> : null}
    </div>
  );
};
