// packages/create/templates/starter-source/react/src/components/features/status-page/StatusPage.tsx
import { Button } from '../../ui';

import type { FC } from 'react';

export interface StatusPageProps {
  readonly code: number;
  readonly message: string;
  readonly onRetry?: () => void;
}

// Home is a full load, so a crash leaves no state behind.
export const StatusPage: FC<StatusPageProps> = ({
  code,
  message,
  onRetry,
}) => {
  return (
    <main className="hero">
      <h1 className="title">{code}</h1>
      <p className="lede" role="alert">{message}</p>
      <p className="hint">
        {onRetry === undefined ? null : <Button onClick={onRetry}>Try again</Button>}
        {' '}
        <a href="/">Go home</a>
      </p>
    </main>
  );
};

// packages/create/templates/starter-source/svelte/src/components/features/status-page/StatusPage.svelte
<script lang="ts">
  import { resolve } from '$app/paths';

  import Button from '../../ui/button/Button.svelte';

  interface Props {
    code: number;
    message: string;
    onretry?: () => void;
  }

  const {
    code,
    message,
    onretry,
  }: Props = $props();
</script>

<!-- Home is a full load, so a crash leaves no state behind. -->
<main class="hero">
  <h1 class="title">{code}</h1>
  <p class="lede" role="alert">{message}</p>
  <p class="hint">
    {#if onretry}
      <Button onclick={onretry}>Try again</Button>
    {/if}
    <a href={resolve('/')} data-sveltekit-reload>Go home</a>
  </p>
</main>
