// packages/create/templates/starter-source/react/i18n/src/pages/about/AboutPage.tsx
import { Trans, useTranslation } from 'react-i18next';

import { CHECK, GATE } from '../../config/linteljs';
import { STANDARD_PATHS } from '../../config/standard';

import type { FC } from 'react';

const CODE = { code: <code /> };

export const AboutPage: FC = () => {
  const { t } = useTranslation();

  return (
    <main className="page">
      <h1 className="page-title">{t('about')}</h1>
      <p className="page-lede">{t('aboutLede')}</p>

      <section className="section">
        <h2 className="section-title">{t('aboutGate')}</h2>
        <ul className="rows">
          {GATE
            .map(({ command, runs }) => {
              return (
                <li key={command} className="row">
                  <code className="key">{command}</code>
                  <span className="value">{runs}</span>
                </li>
              );
            })}
        </ul>
        <p className="note">
          <Trans
            i18nKey="aboutCheck"
            values={{ command: CHECK }}
            components={CODE}
          />
        </p>
      </section>

      <section className="section">
        <h2 className="section-title">{t('aboutStandard')}</h2>
        <dl className="rows">
          {STANDARD_PATHS
            .map(({ path, holds }) => {
              return (
                <div key={path} className="row">
                  <dt><code>{path}</code></dt>
                  <dd>{t(holds)}</dd>
                </div>
              );
            })}
        </dl>
      </section>

      <section className="section">
        <h2 className="section-title">{t('aboutCurrent')}</h2>
        <p className="note">
          <Trans
            i18nKey="aboutSync"
            values={{ command: 'npx @linteljs/create sync' }}
            components={CODE}
          />
        </p>
      </section>
    </main>
  );
};

// packages/create/templates/starter-source/solid/i18n/src/pages/about/AboutPage.tsx
import { For, type JSX } from 'solid-js';

import { CodeText } from '../../components/ui/code-text/CodeText';
import { CHECK, GATE } from '../../config/linteljs';
import { STANDARD_PATHS } from '../../config/standard';
import { t } from '../../i18n';

export const AboutPage = (): JSX.Element => {
  return (
    <main class="page">
      <h1 class="page-title">{t('about')}</h1>
      <p class="page-lede">{t('aboutLede')}</p>

      <section class="section">
        <h2 class="section-title">{t('aboutGate')}</h2>
        <ul class="rows">
          <For each={GATE}>
            {(leg) => {
              return (
                <li class="row">
                  <code class="key">{leg.command}</code>
                  <span class="value">{leg.runs}</span>
                </li>
              );
            }}
          </For>
        </ul>
        <p class="note">
          <CodeText text={t('aboutCheck', { command: CHECK })} />
        </p>
      </section>

      <section class="section">
        <h2 class="section-title">{t('aboutStandard')}</h2>
        <dl class="rows">
          <For each={STANDARD_PATHS}>
            {(entry) => {
              return (
                <div class="row">
                  <dt><code>{entry.path}</code></dt>
                  <dd>{t(entry.holds)}</dd>
                </div>
              );
            }}
          </For>
        </dl>
      </section>

      <section class="section">
        <h2 class="section-title">{t('aboutCurrent')}</h2>
        <p class="note">
          <CodeText text={t('aboutSync', { command: 'npx @linteljs/create sync' })} />
        </p>
      </section>
    </main>
  );
};
