// packages/create/templates/starter-source/solid/i18n/src/pages/contact/ContactPage.tsx
import { Button, TextInput } from '../../components/ui';
import { t } from '../../i18n';

import { useContactForm } from './useContactForm';

import type { JSX } from 'solid-js';

export const ContactPage = (): JSX.Element => {
  const form = useContactForm();

  return (
    <main class="page">
      <h1 class="page-title">{t('contact')}</h1>
      <p class="page-lede">{t('contactLede')}</p>

      {form.sent()
        ? <p class="sent" role="status">{t('contactSent')}</p>
        : (
            <form novalidate onSubmit={form.onSubmit}>
              <TextInput {...form.fields.email} />
              <TextInput {...form.fields.message} />
              <Button type="submit" disabled={!form.canSubmit()}>{t('contactSend')}</Button>
            </form>
          )}
    </main>
  );
};

// packages/create/templates/starter-source/react/i18n/src/pages/contact/ContactPage.tsx
import { useTranslation } from 'react-i18next';

import { Button, TextInput } from '../../components/ui';

import { useContactForm } from './useContactForm';

import type { FC } from 'react';

export const ContactPage: FC = () => {
  const { t } = useTranslation();
  const {
    fields,
    sent,
    submitting,
    canSubmit,
    onSubmit,
  } = useContactForm();

  return (
    <main className="page">
      <h1 className="page-title">{t('contact')}</h1>
      <p className="page-lede">{t('contactLede')}</p>

      {sent
        ? (
            <p className="sent" role="status">{t('contactSent')}</p>
          )
        : (
            <form noValidate onSubmit={onSubmit}>
              <TextInput {...fields.email} />
              <TextInput {...fields.message} />
              <Button type="submit" disabled={!canSubmit || submitting}>{t('contactSend')}</Button>
            </form>
          )}
    </main>
  );
};
