// packages/create/templates/starter-source/react/tanstack-query/src/lib/providers/data/DataProvider.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import type { FC, ReactNode } from 'react';

export interface DataProviderProps {
  readonly children: ReactNode;
}

// One client for the application, made once rather than per render.
const client = new QueryClient();

export const DataProvider: FC<DataProviderProps> = ({ children }) => {
  return <QueryClientProvider client={client}>{children}</QueryClientProvider>;
};

// packages/create/templates/starter-source/solid/src/lib/providers/data/DataProvider.tsx
import type { JSX } from 'solid-js';

export interface DataProviderProps {
  readonly children: JSX.Element;
}

export const DataProvider = (props: DataProviderProps): JSX.Element => {
  // Wrapped rather than returned: reading `props.children` outside JSX reads it once and never again.
  return <>{props.children}</>;
};
