// packages/create/templates/starter-source/astro/solid/src/views/contact/ContactIsland.tsx
import { DataProvider } from '@lib/providers/data/DataProvider';

import { ContactPage } from './ContactPage';

import type { JSX } from 'solid-js';

// An island is its own Solid root, so it brings its provider.
export const ContactIsland = (): JSX.Element => {
  return (
    <DataProvider>
      <ContactPage />
    </DataProvider>
  );
};

// packages/create/templates/starter-source/astro/src/views/contact/ContactIsland.tsx
import { DataProvider } from '@lib/providers/data/DataProvider';

import { ContactPage } from './ContactPage';

import type { FC } from 'react';

// An island is its own React root, so it brings its provider.
export const ContactIsland: FC = () => {
  return (
    <DataProvider>
      <ContactPage />
    </DataProvider>
  );
};
