// packages/create/templates/starter-source/react/react-router-i18n/src/components/features/app-header/AppHeader.tsx
import { useTranslation } from 'react-i18next';
import { NavLink } from 'react-router';

import { ROUTES } from '@router/router';

import { LanguageSelect } from '../language-select/LanguageSelect';

import { styles } from './appHeaderStyles';

import type { FC } from 'react';

export interface AppHeaderProps {
  readonly name: string;
}

export const AppHeader: FC<AppHeaderProps> = ({ name }) => {
  const { t } = useTranslation();

  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>{t('starterLabel')}</p>
      <p {...styles.brand}>{name}</p>
      <nav {...styles.tabs} aria-label="Main">
        {ROUTES
          .map(({
            id,
            path,
          }) => {
            return (
              <NavLink
                key={id}
                to={path}
                end
                className={({ isActive }) => {
                  return styles.tab(isActive).className;
                }}
                style={({ isActive }) => {
                  return styles.tab(isActive).style;
                }}
              >
                {/* Keyed by route id, so a page added to `ROUTES` needs its own key in every locale. */}
                {t(id)}
              </NavLink>
            );
          })}
      </nav>
      <LanguageSelect {...styles.tab(false)} />
    </header>
  );
};

// packages/create/templates/starter-source/solid/i18n/src/components/features/app-header/AppHeader.tsx
import { For, type JSX } from 'solid-js';

import { t, translateId } from '@i18n/i18n';

import { ROUTES } from '@router/router';

import { LanguageSelect } from '../language-select/LanguageSelect';

import { styles } from './appHeaderStyles';

export interface AppHeaderProps {
  readonly name: string;
  readonly current: string;
  readonly onNavigate: (page: string) => void;
}

// Controls rather than links: they swap a view rather than navigating.
export const AppHeader = (props: AppHeaderProps): JSX.Element => {
  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>{t('starterLabel')}</p>
      <p {...styles.brand}>{props.name}</p>
      <nav {...styles.tabs} aria-label="Main">
        <For each={ROUTES}>
          {(route) => {
            return (
              <button
                {...styles.tab(route.id === props.current)}
                type="button"
                aria-current={route.id === props.current ? 'page' : undefined}
                onClick={() => {
                  props.onNavigate(route.id);
                }}
              >
                {translateId(route.id)}
              </button>
            );
          }}
        </For>
      </nav>
      <LanguageSelect {...styles.tab(false)} />
    </header>
  );
};
