// packages/create/templates/starter-source/react/src/components/ui/button/Button.tsx
import { styles } from './styles';

import type { FC, ReactNode } from 'react';

export interface ButtonProps {
  readonly children: ReactNode;
  readonly onClick?: () => void;
  // A form's submit is the one that is not a plain button; everything else presses and does something now.
  readonly type?: 'button' | 'submit';
  readonly disabled?: boolean;
}

export const Button: FC<ButtonProps> = ({
  children,
  onClick,
  type = 'button',
  disabled = false,
}) => {
  return (
    <button
      {...styles.button}
      type={type}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  );
};

// packages/create/templates/starter-source/svelte/src/components/ui/button/Button.svelte
<script lang="ts">
  import { styles } from './styles';

  import type { Snippet } from 'svelte';

  interface Props {
    children: Snippet;
    onclick?: () => void;
    // A form's submit is the one that is not a plain button; everything else presses and does something now.
    type?: 'button' | 'submit';
    disabled?: boolean;
  }

  const {
    children,
    onclick,
    type = 'button',
    disabled = false,
  }: Props = $props();
</script>

<button {...styles.button} {type} {disabled} {onclick}>
  {@render children()}
</button>
