// packages/create/templates/starter-source/react/i18n/src/pages/home/HomePage.tsx
import { Trans, useTranslation } from 'react-i18next';

import { CHECK } from '@config/linteljs';

import { Mark } from '@ui';

import type { FC } from 'react';

export interface HomePageProps {
  readonly name: string;
}

const CODE = { code: <code /> };
const CHECK_VALUES = { command: CHECK };

export const HomePage: FC<HomePageProps> = ({ name }) => {
  const { t } = useTranslation();

  return (
    <main className="hero">
      <Mark />
      <h1 className="title">{name}</h1>
      <p className="lede">{t('homeLedeReact')}</p>
      <p className="hint">
        <Trans
          i18nKey="gateHint"
          values={CHECK_VALUES}
          components={CODE}
          t={t}
        />
      </p>
    </main>
  );
};

// packages/create/templates/starter-source/solid/i18n/src/pages/home/HomePage.tsx
import { CHECK } from '@config/linteljs';

import { t } from '@i18n/i18n';

import { Mark } from '@ui';
import { CodeText } from '@ui/code-text/CodeText';

import type { JSX } from 'solid-js';

export interface HomePageProps {
  readonly name: string;
}

export const HomePage = (props: HomePageProps): JSX.Element => {
  return (
    <main class="hero">
      <Mark />
      <h1 class="title">{props.name}</h1>
      <p class="lede">{t('homeLedeSolid')}</p>
      <p class="hint">
        <CodeText text={t('gateHint', { command: CHECK })} />
      </p>
    </main>
  );
};
