// packages/create/templates/starter-source/react/react-router-i18n/src/components/features/app-header/AppHeader.tsx
import { useTranslation } from 'react-i18next';
import { NavLink } from 'react-router';

import { ROUTES } from '@pages/routes';

import { LanguageSelect } from '../language-select/LanguageSelect';

import { styles } from './appHeaderStyles';

import type { FC } from 'react';

export interface AppHeaderProps {
  readonly name: string;
}

export const AppHeader: FC<AppHeaderProps> = ({ name }) => {
  const { t } = useTranslation();

  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>{t('starterLabel')}</p>
      <p {...styles.brand}>{name}</p>
      <nav {...styles.tabs} aria-label="Main">
        {ROUTES
          .map(({
            id,
            path,
          }) => {
            return (
              <NavLink
                key={id}
                to={path}
                end
                className={({ isActive }) => {
                  return styles.tab(isActive).className;
                }}
                style={({ isActive }) => {
                  return styles.tab(isActive).style;
                }}
              >
                {/* Keyed by route id, so a page added to `ROUTES` needs its own key in every locale. */}
                {t(id)}
              </NavLink>
            );
          })}
      </nav>
      <LanguageSelect {...styles.tab(false)} />
    </header>
  );
};

// packages/create/templates/starter-source/nuxt/i18n/src/components/features/app-header/AppHeader.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';

import { useI18n } from 'vue-i18n';

import { PAGES } from '@config/routes';

import LanguageSelect from '../language-select/LanguageSelect.vue';

import { styles } from './appHeaderStyles';

interface Props {
  name: string;
}

defineProps<Props>();

// Imported, not auto-imported: vitest runs outside Nuxt's build and has no auto-import to resolve.
const route = useRoute();
const { t } = useI18n();
</script>

<!-- `NuxtLink` prefetches a route and keeps the address bar honest. -->
<template>
  <header v-bind="styles.header">
    <p v-bind="styles.starterLabel">
      {{ t('starterLabel') }}
    </p>
    <p v-bind="styles.brand">
      {{ name }}
    </p>
    <nav
      v-bind="styles.tabs"
      aria-label="Main"
    >
      <NuxtLink
        v-for="page in PAGES"
        :key="page.id"
        v-bind="styles.tab(route.path === page.path)"
        :to="page.path"
        :aria-current="route.path === page.path ? 'page' : undefined"
      >
        {{ t(page.id) }}
      </NuxtLink>
    </nav>
    <LanguageSelect v-bind="styles.tab(false)" />
  </header>
</template>
