// packages/create/templates/starter-source/vue/src/components/ui/text-input/TextInput.vue
<script setup lang="ts">
import { computed } from 'vue';

import { styles } from './textInputStyles';

import type { TextInputProps } from './types';

interface Emits {
  change: [value: string];
  blur: [];
}

const props = withDefaults(defineProps<TextInputProps>(), {
  multiline: false,
  type: 'text',
});

const emit = defineEmits<Emits>();

const invalid = computed(() => {
  return props.error !== undefined;
});
const describedBy = computed(() => {
  return props.error === undefined ? undefined : `${props.id}-error`;
});

const model = computed({
  get: () => {
    return props.value;
  },
  set: (value: string) => {
    emit('change', value);
  },
});
</script>

<!-- A dense tool pane can get away with `aria-label` alone; a form cannot. -->
<template>
  <div v-bind="styles.field">
    <label
      v-bind="styles.label"
      :for="id"
    >{{ label }}</label>
    <textarea
      v-if="multiline"
      :id="id"
      v-model="model"
      v-bind="styles.textarea(invalid)"
      :name="id"
      :aria-invalid="invalid"
      :aria-describedby="describedBy"
      @blur="emit('blur')"
    />
    <input
      v-else
      :id="id"
      v-model="model"
      v-bind="styles.input(invalid)"
      :name="id"
      :type="type"
      :aria-invalid="invalid"
      :aria-describedby="describedBy"
      @blur="emit('blur')"
    >
    <p
      v-if="error !== undefined"
      v-bind="styles.error"
      :id="`${id}-error`"
    >
      {{ error }}
    </p>
  </div>
</template>

// packages/create/templates/starter-source/svelte/src/components/ui/text-input/TextInput.svelte
<script lang="ts">
  import { styles } from './textInputStyles';

  import type { TextInputProps } from './types';

  const {
    id,
    label,
    value,
    onChange,
    onBlur,
    error,
    multiline = false,
    type = 'text',
  }: TextInputProps = $props();

  const describedBy = $derived(error === undefined ? undefined : `${id}-error`);
</script>

<!-- A dense tool pane can get away with `aria-label` alone; a form cannot. -->
<div {...styles.field}>
  <label {...styles.label} for={id}>{label}</label>
  {#if multiline}
    <textarea
      {id}
      {...styles.textarea(error !== undefined)}
      name={id}
      {value}
      aria-invalid={error !== undefined}
      aria-describedby={describedBy}
      onblur={onBlur}
      oninput={(event) => {
        onChange(event.currentTarget.value);
      }}
    ></textarea>
  {:else}
    <input
      {id}
      {...styles.input(error !== undefined)}
      name={id}
      {type}
      {value}
      aria-invalid={error !== undefined}
      aria-describedby={describedBy}
      onblur={onBlur}
      oninput={(event) => {
        onChange(event.currentTarget.value);
      }}
    />
  {/if}
  {#if error !== undefined}
    <p {...styles.error} id={`${id}-error`}>{error}</p>
  {/if}
</div>
