// packages/create/templates/starter-source/react/src/lib/providers/DataProvider.tsx
import type { FC, ReactNode } from 'react';

export interface DataProviderProps {
  readonly children: ReactNode;
}

/*
 * The slot a data layer fills. With none, and with RTK Query (whose provider is the Redux one beside it), there is
 * nothing to provide, so this passes its children through.
 *
 * It is here rather than inside the entry for the reason `StoreProvider` is: the entry would otherwise vary by the
 * router, the store and the data layer at once, which is a copy per combination instead of a file per answer.
 */
export const DataProvider: FC<DataProviderProps> = ({ children }) => {
  return children;
};

// packages/create/templates/starter-source/solid/src/lib/providers/DataProvider.tsx
import type { JSX } from 'solid-js';

export interface DataProviderProps {
  readonly children: JSX.Element;
}

/*
 * The slot a data layer fills. With none there is nothing to provide, so this passes its children through
 * and TanStack Query replaces this file with its own client.
 */
export const DataProvider = (props: DataProviderProps): JSX.Element => {
  // Wrapped rather than returned: reading `props.children` outside JSX reads it once and never again.
  return <>{props.children}</>;
};
