// packages/create/templates/starter-source/svelte/i18n/src/routes/about/+page.svelte
<script lang="ts">
  import { CHECK, GATE } from '@config/linteljs';
  import { STANDARD_PATHS } from '@config/standard';

  import { m } from '@i18n';

  import CodeText from '@ui/code-text/CodeText.svelte';
</script>

<main class="page">
  <h1 class="page-title">{m.about()}</h1>
  <p class="page-lede">{m.aboutLede()}</p>

  <section class="section">
    <h2 class="section-title">{m.aboutGate()}</h2>
    <ul class="rows">
      {#each GATE as leg (leg.command)}
        <li class="row">
          <code class="key">{leg.command}</code>
          <span class="value">{leg.runs}</span>
        </li>
      {/each}
    </ul>
    <p class="note">
      <CodeText text={m.aboutCheck({ command: CHECK })} />
    </p>
  </section>

  <section class="section">
    <h2 class="section-title">{m.aboutStandard()}</h2>
    <dl class="rows">
      {#each STANDARD_PATHS as entry (entry.path)}
        <div class="row">
          <dt><code>{entry.path}</code></dt>
          <dd>{m[entry.holds]()}</dd>
        </div>
      {/each}
    </dl>
  </section>

  <section class="section">
    <h2 class="section-title">{m.aboutCurrent()}</h2>
    <p class="note">
      <CodeText text={m.aboutSync({ command: 'npx @linteljs/create sync' })} />
    </p>
  </section>
</main>

// packages/create/templates/starter-source/next/i18n/src/app/about/page.tsx
'use client';

import { useTranslations } from 'next-intl';

import { CHECK, GATE } from '../../config/linteljs';
import { STANDARD_PATHS } from '../../config/standard';

import type { ReactNode } from 'react';

const code = (chunks: ReactNode): ReactNode => {
  return <code>{chunks}</code>;
};

// A client component, so it speaks the reader's language.
const AboutPage = (): ReactNode => {
  const t = useTranslations();

  return (
    <main className="page">
      <h1 className="page-title">{t('about')}</h1>
      <p className="page-lede">{t('aboutLede')}</p>

      <section className="section">
        <h2 className="section-title">{t('aboutGate')}</h2>
        <ul className="rows">
          {GATE
            .map(({ command, runs }) => {
              return (
                <li key={command} className="row">
                  <code className="key">{command}</code>
                  <span className="value">{runs}</span>
                </li>
              );
            })}
        </ul>
        <p className="note">
          {t.rich('aboutCheck', {
            command: CHECK,
            code,
          })}
        </p>
      </section>

      <section className="section">
        <h2 className="section-title">{t('aboutStandard')}</h2>
        <dl className="rows">
          {STANDARD_PATHS
            .map(({ path, holds }) => {
              return (
                <div key={path} className="row">
                  <dt><code>{path}</code></dt>
                  <dd>{t(holds)}</dd>
                </div>
              );
            })}
        </dl>
      </section>

      <section className="section">
        <h2 className="section-title">{t('aboutCurrent')}</h2>
        <p className="note">
          {t.rich('aboutSync', {
            command: 'npx @linteljs/create sync',
            code,
          })}
        </p>
      </section>
    </main>
  );
};

export default AboutPage;
