// packages/create/templates/starter-source/react/i18n/src/components/features/status-page/StatusPage.tsx
import { useTranslation } from 'react-i18next';

import { Button } from '@ui';

import type { FC } from 'react';

export interface StatusPageProps {
  readonly code: number;
  // A key into `src/i18n/locales/`, as `STATUSES` holds it.
  readonly message: string;
  readonly onRetry?: () => void;
}

// Home is a full load, so a crash leaves no state behind.
export const StatusPage: FC<StatusPageProps> = ({
  code,
  message,
  onRetry,
}) => {
  const { t } = useTranslation();

  return (
    <main className="status">
      <h1 className="status-code">{code}</h1>
      <p className="status-message" role="alert">{t(message)}</p>
      <div className="status-actions">
        {onRetry === undefined ? null : <Button onClick={onRetry}>{t('statusRetry')}</Button>}
        <a
          className={onRetry === undefined
            ? 'status-action'
            : 'status-action status-action-outline'}
          href="/"
        >
          {t('statusHome')}
        </a>
      </div>
    </main>
  );
};

// packages/create/templates/starter-source/svelte/i18n/src/components/features/status-page/StatusPage.svelte
<script lang="ts">
  import { resolve } from '$app/paths';

  import { m } from '../../../i18n';
  import Button from '../../ui/button/Button.svelte';

  import type { STATUSES } from '../../../config/statuses';

  interface Props {
    code: number;
    message: (typeof STATUSES)[keyof typeof STATUSES]['message'];
    onretry?: () => void;
  }

  const {
    code,
    message,
    onretry,
  }: Props = $props();
</script>

<!-- Home is a full load, so a crash leaves no state behind. -->
<main class="status">
  <h1 class="status-code">{code}</h1>
  <p class="status-message" role="alert">{m[message]()}</p>
  <div class="status-actions">
    {#if onretry}
      <Button onclick={onretry}>{m.statusRetry()}</Button>
    {/if}
    <a
      class={['status-action', onretry && 'status-action-outline']}
      href={resolve('/')}
      data-sveltekit-reload
    >
      {m.statusHome()}
    </a>
  </div>
</main>
