// packages/create/templates/starter-source/vue/i18n/src/components/features/status-page/StatusPage.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';

import AppButton from '@ui/app-button/AppButton.vue';

interface Props {
  code: number;
  message: string;
  // A prop rather than an emit, so the page knows whether anything listens.
  onRetry?: () => void;
}

defineProps<Props>();

const { t } = useI18n();
</script>

<!-- Home is a full load, so a crash leaves no state behind. -->
<template>
  <main class="status">
    <h1 class="status-code">
      {{ code }}
    </h1>
    <p
      class="status-message"
      role="alert"
    >
      {{ t(message) }}
    </p>
    <div class="status-actions">
      <AppButton
        v-if="onRetry"
        @click="onRetry"
      >
        {{ t('statusRetry') }}
      </AppButton>
      <a
        :class="['status-action', { 'status-action-outline': onRetry }]"
        href="/"
      >
        {{ t('statusHome') }}
      </a>
    </div>
  </main>
</template>

// packages/create/templates/starter-source/svelte/i18n/src/components/features/status-page/StatusPage.svelte
<script lang="ts">
  import { resolve } from '$app/paths';

  import { m } from '../../../i18n';
  import Button from '../../ui/button/Button.svelte';

  import type { STATUSES } from '../../../config/statuses';

  interface Props {
    code: number;
    message: (typeof STATUSES)[keyof typeof STATUSES]['message'];
    onretry?: () => void;
  }

  const {
    code,
    message,
    onretry,
  }: Props = $props();
</script>

<!-- Home is a full load, so a crash leaves no state behind. -->
<main class="status">
  <h1 class="status-code">{code}</h1>
  <p class="status-message" role="alert">{m[message]()}</p>
  <div class="status-actions">
    {#if onretry}
      <Button onclick={onretry}>{m.statusRetry()}</Button>
    {/if}
    <a
      class={['status-action', onretry && 'status-action-outline']}
      href={resolve('/')}
      data-sveltekit-reload
    >
      {m.statusHome()}
    </a>
  </div>
</main>
