// packages/create/templates/starter-source/react/tanstack-router/src/App.tsx
import {
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
  RouterProvider,
} from '@tanstack/react-router';

import { AppHeader } from './components/features/app-header/AppHeader';
import { NAME } from './config/linteljs';
import { ROUTES } from './pages/routes';

import type { FC } from 'react';

// The header is outside the routes, so it renders once and every route fills what sits under it.
const rootRoute = createRootRoute({
  component: () => {
    return (
      <>
        <AppHeader name={NAME} />
        <Outlet />
      </>
    );
  },
});

/*
 * Built from the one route list rather than from a `routes/` directory and a generated tree. File-based routing is
 * this library's own default, and it is declined here for one reason: the tree would be a second list of the pages,
 * and the form answer adds a page, so the generated file would need a copy per combination of router and form.
 * Reading the array the header reads keeps that a sum, and a project that wants the generated tree adds the plugin.
 */
const router = createRouter({
  routeTree: rootRoute.addChildren(ROUTES
    .map(({ path, element }) => {
      return createRoute({
        getParentRoute: () => {
          return rootRoute;
        },
        path,
        component: () => {
          return element;
        },
      });
    })),
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

/*
 * With a router this is the whole of the app: the route table owns which page renders, and the header's tabs are
 * real links, so the address bar follows. The pages themselves are the same files the no-router build uses.
 */
export const App: FC = () => {
  return <RouterProvider router={router} />;
};

// packages/create/templates/starter-source/solid/src/App.tsx
import {
  createSignal,
  type JSX,
  Show,
} from 'solid-js';

import { AppHeader } from './components/features/app-header/AppHeader';
import { NAME } from './config/linteljs';
import { ROUTES } from './pages/routes';

export interface AppProps {
  readonly initialPage?: string;
}

/*
 * The header swaps this from a signal and the address bar never moves. Solid routes with `@solidjs/router` when a
 * project wants one; the pages are the same files either way.
 *
 * `props` is read rather than destructured: taking `initialPage` out of it once would read it once and never
 * again, which is the reactivity rule this target's own `solid-reactivity.md` carries.
 */
export const App = (props: AppProps): JSX.Element => {
  const [page, setPage] = createSignal(props.initialPage ?? ROUTES[0].id);
  const current = () => {
    return ROUTES
      .find((route) => {
        return route.id === page();
      });
  };

  return (
    <>
      <AppHeader
        name={NAME}
        current={page()}
        onNavigate={setPage}
      />
      {/* `keyed`: without it the block is built once and switching to another page re-renders the first one. */}
      <Show when={current()} keyed>
        {(route) => {
          return route.element();
        }}
      </Show>
    </>
  );
};
