// packages/create/templates/starter-source/astro/svelte-i18n/src/views/contact/ContactIsland.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import DataProvider from '#lib/providers/data/DataProvider.svelte';

  import { fallbackLanguage } from '@i18n/config';

  import ContactPage from './ContactPage.svelte';

  import type { ContactCopy, ContactCopyKey } from './utils/contactCopyUtils';

  interface Props {
    copy: ContactCopy;
  }

  const { copy }: Props = $props();

  // The build language until mounted, so hydration matches; then `<html lang>`, which the switcher sets.
  let language = $state<string>(fallbackLanguage);

  onMount(() => {
    const follow = (): void => {
      language = document.documentElement.lang;
    };

    const observer = new MutationObserver(follow);

    follow();

    observer.observe(document.documentElement, { attributeFilter: ['lang'] });

    return () => {
      observer.disconnect();
    };
  });

  const phrase = (key: ContactCopyKey): string => {
    return copy[language]?.[key] ?? key;
  };
</script>

<!-- An island is its own Svelte root, so it brings its provider. -->
<DataProvider>
  <ContactPage {phrase} />
</DataProvider>

// packages/create/templates/starter-source/astro/i18n/src/views/contact/ContactIsland.vue
<script setup lang="ts">
import {
  getCurrentInstance,
  onBeforeUnmount,
  onMounted,
  ref,
} from 'vue';

import { dataProvider } from '@lib/providers/data/dataProvider';
import { fallbackLanguage } from '@i18n/config';

import ContactPage from './ContactPage.vue';

import type { ContactCopy, ContactCopyKey } from './utils/contactCopyUtils';

interface Props {
  copy: ContactCopy;
}

const props = defineProps<Props>();

// An island is its own Vue app, so it installs the provider its page reads.
getCurrentInstance()?.appContext.app.use(dataProvider);

// The build language until mounted, so hydration matches; then `<html lang>`, which the switcher sets.
const language = ref<string>(fallbackLanguage);

const follow = (): void => {
  language.value = document.documentElement.lang;
};

let observer: MutationObserver | undefined;

onMounted(() => {
  follow();
  observer = new MutationObserver(follow);
  observer.observe(document.documentElement, { attributeFilter: ['lang'] });
});

onBeforeUnmount(() => {
  observer?.disconnect();
});

const phrase = (key: ContactCopyKey): string => {
  return props.copy[language.value]?.[key] ?? key;
};
</script>

<template>
  <ContactPage :phrase="phrase" />
</template>
