// packages/create/templates/starter-source/astro/svelte-i18n/src/views/contact/ContactPage.svelte
<script lang="ts">
  import Button from '@ui/button/Button.svelte';
  import TextInput from '@ui/text-input/TextInput.svelte';

  import { useContactForm } from './use-contact-form/useContactForm';

  import type { ContactCopyKey } from './utils/contactCopyUtils';

  interface Props {
    phrase: (key: ContactCopyKey) => string;
  }

  const { phrase }: Props = $props();

  const form = useContactForm((key) => {
    return phrase(key);
  });
</script>

<main class="page">
  <h1 class="page-title">{phrase('contact')}</h1>
  <p class="page-lede">{phrase('contactLede')}</p>

  {#if form.sent}
    <p class="sent" role="status">{phrase('contactSent')}</p>
  {:else}
    <form novalidate onsubmit={form.onSubmit}>
      <TextInput {...form.fields.email} />
      <TextInput {...form.fields.message} />
      <Button type="submit" disabled={!form.canSubmit}>{phrase('contactSend')}</Button>
    </form>
  {/if}
</main>

// packages/create/templates/starter-source/astro/i18n/src/views/contact/ContactPage.tsx
import { Button, TextInput } from '@ui';

import { useContactForm } from './use-contact-form/useContactForm';

import type { FC } from 'react';
import type { ContactCopyKey } from './utils/contactCopyUtils';

interface ContactPageProps {
  readonly translate: (key: ContactCopyKey) => string;
}

export const ContactPage: FC<ContactPageProps> = ({ translate }) => {
  const {
    fields,
    sent,
    submitting,
    canSubmit,
    onSubmit,
  } = useContactForm(translate);

  return (
    <main className="page">
      <h1 className="page-title">{translate('contact')}</h1>
      <p className="page-lede">{translate('contactLede')}</p>

      {sent
        ? (
            <p className="sent" role="status">{translate('contactSent')}</p>
          )
        : (
            <form noValidate onSubmit={onSubmit}>
              <TextInput {...fields.email} />
              <TextInput {...fields.message} />
              <Button type="submit" disabled={!canSubmit || submitting}>{translate('contactSend')}</Button>
            </form>
          )}
    </main>
  );
};
