// packages/create/templates/starter-source/solid/tanstack-store/src/lib/store/counter.ts
import { Store, useSelector } from '@tanstack/solid-store';

import type { Accessor } from 'solid-js';

export interface CounterState {
  count: number;
}

export interface Counter {
  count: Accessor<number>;
  add: () => void;
}

const store = new Store<CounterState>({ count: 0 });

/*
 * The one store this starter ships, and the one place the store answer is visible. Every other file takes
 * `useCounter` and never knows which library is behind it.
 *
 * Solid's own `createStore` covers state inside a component; this is for what crosses one, which is why the
 * target offers a library here rather than the built-in.
 */
export const useCounter = (): Counter => {
  const count = useSelector(store, (state) => {
    return state.count;
  });

  return {
    count,
    add: () => {
      store.setState((state) => {
        return { count: state.count + 1 };
      });
    },
  };
};

// packages/create/templates/starter-source/react/redux-toolkit/src/lib/store/counter.ts
import { useDispatch, useSelector } from 'react-redux';

import { configureStore, createSlice } from '@reduxjs/toolkit';

export interface CounterState {
  count: number;
}

export interface Counter {
  count: number;
  add: () => void;
}

export type RootState = ReturnType<typeof store.getState>;

const counter = createSlice({
  name: 'counter',
  initialState: { count: 0 } satisfies CounterState as CounterState,
  reducers: {
    add: (state) => {
      state.count += 1;
    },
  },
});

export const store = configureStore({ reducer: { counter: counter.reducer } });

/*
 * The one store this starter ships, and the one place the store answer is visible. Every other file takes
 * `useCounter` and never knows which library is behind it, which is what lets the answer change without the pages
 * changing with it.
 */
export const useCounter = (): Counter => {
  const count = useSelector((state: RootState) => {
    return state.counter.count;
  });
  const dispatch = useDispatch();

  return {
    count,
    add: () => {
      dispatch(counter.actions.add());
    },
  };
};
