// packages/create/templates/starter-source/solid/src/components/features/status-page/StatusPage.tsx
import { type JSX, Show } from 'solid-js';

import { Button } from '../../ui';

export interface StatusPageProps {
  readonly code: number;
  readonly message: string;
  readonly onRetry?: () => void;
}

// Home is a full load, so a crash leaves no state behind.
export const StatusPage = (props: StatusPageProps): JSX.Element => {
  return (
    <main class="status">
      <h1 class="status-code">{props.code}</h1>
      <p class="status-message" role="alert">{props.message}</p>
      <div class="status-actions">
        <Show when={props.onRetry}>
          {(retry) => {
            return <Button onClick={retry()}>Try again</Button>;
          }}
        </Show>
        <a
          class="status-action"
          classList={{ 'status-action-outline': props.onRetry !== undefined }}
          href="/"
        >
          Go home
        </a>
      </div>
    </main>
  );
};

// packages/create/templates/starter-source/react/src/components/features/status-page/StatusPage.tsx
import { Button } from '../../ui';

import type { FC } from 'react';

export interface StatusPageProps {
  readonly code: number;
  readonly message: string;
  readonly onRetry?: () => void;
}

// Home is a full load, so a crash leaves no state behind.
export const StatusPage: FC<StatusPageProps> = ({
  code,
  message,
  onRetry,
}) => {
  return (
    <main className="status">
      <h1 className="status-code">{code}</h1>
      <p className="status-message" role="alert">{message}</p>
      <div className="status-actions">
        {onRetry === undefined ? null : <Button onClick={onRetry}>Try again</Button>}
        <a
          className={onRetry === undefined
            ? 'status-action'
            : 'status-action status-action-outline'}
          href="/"
        >
          Go home
        </a>
      </div>
    </main>
  );
};
