// packages/create/templates/starter-source/svelte/src/routes/version/+page.svelte
<script lang="ts">
  import { ANSWERS, STACK } from '@config/linteljs';
</script>

<!-- Recorded when the project was generated: a browser cannot read its machine's Node or package manager. -->
<main class="page">
  <h1 class="page-title">Version</h1>
  <p class="page-lede">What this project is running, and the answers it was generated from.</p>

  <section class="section">
    <h2 class="section-title">Stack</h2>
    <dl class="rows">
      {#each STACK as entry (entry.name)}
        <div class="row">
          <dt>{entry.name}</dt>
          <dd>{entry.version}</dd>
        </div>
      {/each}
    </dl>
  </section>

  <section class="section">
    <h2 class="section-title">Your answers</h2>
    <dl class="rows">
      {#each ANSWERS as entry (entry.label)}
        <div class="row">
          <dt>{entry.label}</dt>
          <dd>{entry.value}</dd>
        </div>
      {/each}
    </dl>
    <p class="note">
      Recorded in <code>linteljs.config.json</code>, which <code>sync</code> reads.
    </p>
  </section>
</main>

// packages/create/templates/starter-source/react-native/src/app/version.tsx
import {
  ScrollView,
  Text,
  View,
} from 'react-native';

import { ANSWERS, STACK } from '@config/linteljs';
import { useStarterStyles } from '@styles/starter';

import type { ReactNode } from 'react';

// Recorded when the project was generated: a device cannot read that machine.
const VersionScreen = (): ReactNode => {
  const { layout, text } = useStarterStyles();

  return (
    <ScrollView style={layout.screen} role="main">
      <Text style={text.pageTitle}>Version</Text>
      <Text style={text.lede}>What this project is running, and the answers it was generated from.</Text>

      <Text style={text.sectionTitle}>Stack</Text>
      {STACK
        .map((entry) => {
          return (
            <View key={entry.name} style={layout.row}>
              <Text style={text.key}>{entry.name}</Text>
              <Text style={text.value}>{entry.version}</Text>
            </View>
          );
        })}

      <Text style={text.sectionTitle}>Your answers</Text>
      {ANSWERS
        .map((entry) => {
          return (
            <View key={entry.label} style={layout.row}>
              <Text style={text.key}>{entry.label}</Text>
              <Text style={text.value}>{entry.value}</Text>
            </View>
          );
        })}
    </ScrollView>
  );
};

export default VersionScreen;
