// packages/create/templates/starter-source/react/i18n/src/components/features/language-select/LanguageSelect.tsx
import { useTranslation } from 'react-i18next';

import { languages } from '@i18n/config';
import { chooseLanguage } from '@i18n/i18n';

import type { ComponentProps, FC } from 'react';

export type LanguageSelectProps = Pick<ComponentProps<'select'>, 'className' | 'style'>;

// Styled by the header that holds it, so every header keeps one visual language.
export const LanguageSelect: FC<LanguageSelectProps> = (props) => {
  const { t, i18n } = useTranslation();

  return (
    <select
      {...props}
      aria-label={t('language')}
      value={i18n.language}
      onChange={(event) => {
        void chooseLanguage(event.target.value);
      }}
    >
      {languages
        .map(({ id, label }) => {
          return (
            <option
              key={id}
              value={id}
              lang={id}
            >
              {label}
            </option>
          );
        })}
    </select>
  );
};

// packages/create/templates/starter-source/vue/i18n/src/components/features/language-select/LanguageSelect.vue
<script setup lang="ts">
import { computed } from 'vue';

import { chooseLanguage } from '@i18n';
import { languages } from '@i18n/config';
import { useI18n } from 'vue-i18n';

const { t, locale } = useI18n();

const language = computed({
  get: () => {
    return locale.value;
  },
  set: chooseLanguage,
});
</script>

<!-- Styled by the header that holds it, so every header keeps one visual language. -->
<template>
  <select
    v-model="language"
    :aria-label="t('language')"
  >
    <option
      v-for="option in languages"
      :key="option.id"
      :value="option.id"
      :lang="option.id"
    >
      {{ option.label }}
    </option>
  </select>
</template>
