// packages/create/templates/starter-source/solid/i18n/src/components/features/status-page/StatusPage.tsx
import { type JSX, Show } from 'solid-js';

import { type MessageKey, t } from '../../../i18n';
import { Button } from '../../ui';

export interface StatusPageProps {
  readonly code: number;
  // A key into `src/i18n/locales/`, as `STATUSES` holds it.
  readonly message: MessageKey;
  readonly onRetry?: () => void;
}

// Home is a full load, so a crash leaves no state behind.
export const StatusPage = (props: StatusPageProps): JSX.Element => {
  return (
    <main class="status">
      <h1 class="status-code">{props.code}</h1>
      <p class="status-message" role="alert">{t(props.message)}</p>
      <div class="status-actions">
        <Show when={props.onRetry}>
          {(retry) => {
            return <Button onClick={retry()}>{t('statusRetry')}</Button>;
          }}
        </Show>
        {/* `href` first: Solid writes the template unquoted, and happy-dom reads a closing `href=/>` as empty. */}
        <a
          href="/"
          class="status-action"
          classList={{ 'status-action-outline': props.onRetry !== undefined }}
        >
          {t('statusHome')}
        </a>
      </div>
    </main>
  );
};

// packages/create/templates/starter-source/react/i18n/src/components/features/status-page/StatusPage.tsx
import { useTranslation } from 'react-i18next';

import { Button } from '@ui';

import type { FC } from 'react';

export interface StatusPageProps {
  readonly code: number;
  // A key into `src/i18n/locales/`, as `STATUSES` holds it.
  readonly message: string;
  readonly onRetry?: () => void;
}

// Home is a full load, so a crash leaves no state behind.
export const StatusPage: FC<StatusPageProps> = ({
  code,
  message,
  onRetry,
}) => {
  const { t } = useTranslation();

  return (
    <main className="status">
      <h1 className="status-code">{code}</h1>
      <p className="status-message" role="alert">{t(message)}</p>
      <div className="status-actions">
        {onRetry === undefined ? null : <Button onClick={onRetry}>{t('statusRetry')}</Button>}
        <a
          className={onRetry === undefined
            ? 'status-action'
            : 'status-action status-action-outline'}
          href="/"
        >
          {t('statusHome')}
        </a>
      </div>
    </main>
  );
};
