// packages/create/templates/starter-source/angular/i18n/src/i18n/index.ts
import { signal } from '@angular/core';

import {
  fallbackLanguage,
  languages,
  languageStorageKey,
  resources,
} from './config';

export type Language = (typeof languages)[number]['id'];

export type MessageKey = keyof (typeof resources)[Language]['common'];

const isLanguage = (tag: string | null): tag is Language => {
  return languages.some((option) => {
    return option.id === tag;
  });
};

const current = signal<Language>(fallbackLanguage);

export const language = current.asReadonly();

// Read in a template, so every rendered message follows the language signal.
export const t = (key: MessageKey, values?: Readonly<Record<string, string>>): string => {
  return resources[current()].common[key]
    .replace(/\{(\w+)\}/gu, (match, name: string) => {
      return values?.[name] ?? match;
    });
};

const isMessageKey = (key: string): key is MessageKey => {
  return key in resources[current()].common;
};

// A page id is its own key, so one no locale names yet shows as the id.
export const translateId = (id: string): string => {
  return isMessageKey(id) ? t(id) : id;
};

export const directionOf = (tag: string): 'ltr' | 'rtl' => {
  return languages
    .find((option) => {
      return option.id === tag;
    })?.dir ?? 'ltr';
};

// The stored choice, then the browser's languages, then English. Nothing detected is stored.
export const detectLanguage = (): Language => {
  const stored = localStorage.getItem(languageStorageKey);

  if (isLanguage(stored)) {
    return stored;
  }

  return navigator.languages
    .flatMap((tag) => {
      return [tag, new Intl.Locale(tag).language];
    })
    .find(isLanguage) ?? fallbackLanguage;
};

export const applyLanguage = (next: Language): void => {
  const root = document.documentElement;

  current.set(next);
  root.lang = next;
  root.dir = directionOf(next);
};

// The one writer of the stored choice.
export const chooseLanguage = (tag: string): void => {
  if (!isLanguage(tag)) {
    return;
  }

  localStorage.setItem(languageStorageKey, tag);
  applyLanguage(tag);
};

// packages/create/templates/starter-source/react-native/i18n/src/i18n/index.ts
import { initReactI18next } from 'react-i18next';
import { I18nManager, Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

import i18next from 'i18next';

import {
  fallbackLanguage,
  languages,
  languageStorageKey,
  resources,
} from './config';

export const directionOf = (language: string): 'ltr' | 'rtl' => {
  return languages
    .find((option) => {
      return option.id === language;
    })?.dir ?? 'ltr';
};

// The exact tag, then its base language: `ja-JP` reads as `ja`.
export const matchLanguage = (tag: string | null): string | undefined => {
  const ids: readonly string[] = languages
    .map((option) => {
      return option.id;
    });
  const base = tag?.split('-')[0];

  const exact = ids
    .find((id) => {
      return id === tag;
    });

  return exact ?? ids
    .find((id) => {
      return id === base;
    });
};

// Native lays out its direction at launch, so a switch there shows from the next one on.
export const applyDirection = (language: string): void => {
  const rtl = directionOf(language) === 'rtl';

  if (Platform.OS === 'web') {
    document.documentElement.lang = language;
    document.documentElement.dir = rtl ? 'rtl' : 'ltr';

    return;
  }

  I18nManager.allowRTL(rtl);
  I18nManager.forceRTL(rtl);
};

// The one writer of the stored choice.
export const chooseLanguage = async (language: string): Promise<void> => {
  await AsyncStorage.setItem(languageStorageKey, language);
  await i18next.changeLanguage(language);
};

// The stored choice, then the device's language, then English; nothing detected is stored.
export const detectLanguage = async (): Promise<string> => {
  const stored = matchLanguage(await AsyncStorage.getItem(languageStorageKey));

  return stored ?? matchLanguage(Intl.DateTimeFormat().resolvedOptions().locale) ?? fallbackLanguage;
};

// After the first render: the web export is rendered in English, and hydration has to match it.
export const restoreLanguage = async (): Promise<void> => {
  await i18next.changeLanguage(await detectLanguage());
};

export const initI18n = (): typeof i18next => {
  if (!i18next.isInitialized) {
    void i18next
      .use(initReactI18next)
      .init({
        resources,
        lng: fallbackLanguage,
        fallbackLng: fallbackLanguage,
        defaultNS: 'common',
        initAsync: false,
        // Single braces, as every other target's library reads the same locales.
        interpolation: {
          escapeValue: false,
          prefix: '{',
          suffix: '}',
        },
      });

    i18next.on('languageChanged', applyDirection);
  }

  return i18next;
};
