// packages/create/templates/starter-source/solid/src/components/features/app-header/AppHeader.tsx
import { For, type JSX } from 'solid-js';

import { ROUTES } from '@pages/routes';

import { styles } from './appHeaderStyles';

export interface AppHeaderProps {
  readonly name: string;
  readonly current: string;
  readonly onNavigate: (page: string) => void;
}

// Controls rather than links: they swap a view rather than navigating.
export const AppHeader = (props: AppHeaderProps): JSX.Element => {
  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>LintelJS Starter</p>
      <p {...styles.brand}>{props.name}</p>
      <nav {...styles.tabs} aria-label="Main">
        <For each={ROUTES}>
          {(route) => {
            return (
              <button
                {...styles.tab(route.id === props.current)}
                type="button"
                aria-current={route.id === props.current ? 'page' : undefined}
                onClick={() => {
                  props.onNavigate(route.id);
                }}
              >
                {route.label}
              </button>
            );
          }}
        </For>
      </nav>
    </header>
  );
};

// packages/create/templates/starter-source/react/src/components/features/app-header/AppHeader.tsx
import { ROUTES } from '@pages/routes';

import { styles } from './appHeaderStyles';

import type { FC } from 'react';

export interface AppHeaderProps {
  readonly name: string;
  readonly current: string;
  readonly onNavigate: (page: string) => void;
}

// An element that navigates is an anchor; faking one with a button breaks middle-click.
export const AppHeader: FC<AppHeaderProps> = ({
  name,
  current,
  onNavigate,
}) => {
  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>LintelJS Starter</p>
      <p {...styles.brand}>{name}</p>
      <nav {...styles.tabs} aria-label="Main">
        {ROUTES
          .map(({ id, label }) => {
            return (
              <button
                key={id}
                type="button"
                aria-current={id === current ? 'page' : undefined}
                {...styles.tab(id === current)}
                onClick={() => {
                  onNavigate(id);
                }}
              >
                {label}
              </button>
            );
          })}
      </nav>
    </header>
  );
};
