// packages/create/templates/starter-source/solid/src/pages/contact/useContactForm.ts
import { type Accessor, createSignal } from 'solid-js';

import { createForm } from '@tanstack/solid-form';

import {
  type ContactValues,
  useSubmitContact,
  validateContact,
} from '../../lib/apis/contact';

import type { TextInputProps } from '../../components/ui';

// What this library hands a validator and a submit; named because `createForm` takes its options through a getter
// and TypeScript has no contextual type to infer them from there.
interface ContactSubmission {
  value: ContactValues;
}

export interface ContactFields {
  email: TextInputProps;
  message: TextInputProps;
}

export interface ContactForm {
  fields: ContactFields;
  sent: Accessor<boolean>;
  canSubmit: Accessor<boolean>;
  onSubmit: (event: SubmitEvent) => void;
}

/*
 * The one place the form answer is visible. It hands the page a field per input and a submit, and the page never
 * knows which library bound them, which is what lets the answer change without the page changing with it.
 *
 * The rules come from `lib/apis/contact`, so the form and the api agree about what is valid by reading the same
 * function rather than each carrying a copy of it.
 *
 * Every field is a getter, and the state behind them is one `useSelector`: that is the only read of this library
 * Solid tracks, so a plain `form.getFieldValue` would render the first value and never move again.
 */
export const useContactForm = (): ContactForm => {
  const [sent, setSent] = createSignal(false);
  const submit = useSubmitContact();
  const form = createForm(() => {
    return {
      defaultValues: {
        email: '',
        message: '',
      } satisfies ContactValues as ContactValues,
      validators: {
        onBlur: ({ value }: ContactSubmission) => {
          const found = validateContact(value);

          return Object.keys(found).length > 0 ? { fields: found } : undefined;
        },
      },
      onSubmit: async ({ value }: ContactSubmission) => {
        await submit(value);
        setSent(true);
      },
    };
  });
  const state = form
    .useSelector((current) => {
      return current;
    });

  const field = (
    name: keyof ContactValues,
    label: string,
    extra: Partial<TextInputProps> = {},
  ): TextInputProps => {
    return {
      id: name,
      label,
      ...extra,
      get value() {
        return state().values[name];
      },
      get error() {
        // Read inline: `errors` is an `any[]`, so naming its first element would be an unsafe assignment.
        const meta = state().fieldMeta[name];

        return meta?.errors[0] === undefined ? undefined : String(meta.errors[0]);
      },
      onBlur: () => {
        /*
         * `validateField` answers the errors or a promise of them, and that union satisfies neither rule: left
         * alone it may be a floating promise, and `void` is refused on a value that might not be one. Wrapping
         * settles which it is.
         */
        void Promise.resolve(form.validateField(name, 'blur'));
      },
      onChange: (value) => {
        form.setFieldValue(name, value);
      },
    };
  };

  return {
    fields: {
      email: field('email', 'Email', { type: 'email' }),
      message: field('message', 'Message', { multiline: true }),
    },
    sent,
    canSubmit: () => {
      return state().canSubmit;
    },
    onSubmit: (event) => {
      event.preventDefault();
      void form.handleSubmit();
    },
  };
};

// packages/create/templates/starter-source/react/react-hook-form/src/pages/contact/useContactForm.ts
import { type SubmitEventHandler, useState } from 'react';
import {
  type Control,
  useController,
  useForm,
} from 'react-hook-form';

import {
  type ContactValues,
  useSubmitContact,
  validateContact,
} from '../../lib/apis/contact';

import type { TextInputProps } from '../../components/ui';

export interface ContactFields {
  email: TextInputProps;
  message: TextInputProps;
}

export interface ContactForm {
  fields: ContactFields;
  sent: boolean;
  submitting: boolean;
  canSubmit: boolean;
  // Not `FormEventHandler`: React 19's types deprecate it and name this as what a submit actually takes.
  onSubmit: SubmitEventHandler<HTMLFormElement>;
}

interface FieldOptions {
  control: Control<ContactValues>;
  name: keyof ContactValues;
  label: string;
  multiline?: boolean;
  type?: 'text' | 'email';
}

/*
 * `useController` rather than `register`: the input is controlled, and this is the binding React Hook Form offers
 * for one. `register` spreads onto an uncontrolled element and would need the control to be a different shape.
 */
const useField = ({
  control,
  name,
  label,
  multiline = false,
  type = 'text',
}: FieldOptions): TextInputProps => {
  const { field, fieldState } = useController({
    control,
    name,
  });

  return {
    id: name,
    label,
    multiline,
    type,
    value: field.value,
    error: fieldState.error?.message,
    onBlur: field.onBlur,
    onChange: field.onChange,
  };
};

/*
 * The one place the form answer is visible. It hands the page a field per input and a submit, and the page never
 * knows which library bound them, which is what lets the answer change without the page changing with it.
 *
 * The rules come from `lib/apis/contact` through a resolver, so the form and the api agree about what is valid by
 * reading the same function rather than each carrying a copy of it.
 */
export const useContactForm = (): ContactForm => {
  const [sent, setSent] = useState(false);
  const submit = useSubmitContact();
  const {
    control,
    handleSubmit,
    formState,
  } = useForm<ContactValues>({
    mode: 'onBlur',
    defaultValues: {
      email: '',
      message: '',
    },
    resolver: (values) => {
      const found = validateContact(values);
      const errors = Object.fromEntries(Object.entries(found)
        .map(([name, message]) => {
          return [name, {
            type: 'validate',
            message,
          }];
        }));

      return {
        errors,
        values: Object.keys(found).length > 0 ? {} : values,
      };
    },
  });

  return {
    fields: {
      email: useField({
        control,
        name: 'email',
        label: 'Email',
        type: 'email',
      }),
      message: useField({
        control,
        name: 'message',
        label: 'Message',
        multiline: true,
      }),
    },
    sent,
    submitting: formState.isSubmitting,
    canSubmit: !formState.isSubmitted || formState.isValid,
    /*
     * Wrapped rather than handed over: `handleSubmit` answers a handler that returns a promise, and a submit
     * handler is expected to return nothing, which `no-misused-promises` is right to refuse.
     */
    onSubmit: (event) => {
      void handleSubmit(async (values) => {
        await submit(values);
        setSent(true);
      })(event);
    },
  };
};
