// packages/create/templates/starter-source/react/src/pages/version/VersionPage.tsx
import { ANSWERS, STACK } from '@config/linteljs';

import type { FC } from 'react';

// Recorded when the project was generated: a browser cannot read its machine's Node or package manager.
export const VersionPage: FC = () => {
  return (
    <main className="page">
      <h1 className="page-title">Version</h1>
      <p className="page-lede">What this project is running, and the answers it was generated from.</p>

      <section className="section">
        <h2 className="section-title">Stack</h2>
        <dl className="rows">
          {STACK
            .map(({ name, version }) => {
              return (
                <div key={name} className="row">
                  <dt>{name}</dt>
                  <dd>{version}</dd>
                </div>
              );
            })}
        </dl>
      </section>

      <section className="section">
        <h2 className="section-title">Your answers</h2>
        <dl className="rows">
          {ANSWERS
            .map(({ label, value }) => {
              return (
                <div key={label} className="row">
                  <dt>{label}</dt>
                  <dd>{value}</dd>
                </div>
              );
            })}
        </dl>
        <p className="note">
          Recorded in
          {' '}
          <code>linteljs.config.json</code>
          , which
          {' '}
          <code>sync</code>
          {' '}
          reads.
        </p>
      </section>
    </main>
  );
};

// packages/create/templates/starter-source/solid/src/pages/version/VersionPage.tsx
import { For, type JSX } from 'solid-js';

import { ANSWERS, STACK } from '@config/linteljs';

// Recorded when the project was generated: a browser cannot read its machine's Node or package manager.
export const VersionPage = (): JSX.Element => {
  return (
    <main class="page">
      <h1 class="page-title">Version</h1>
      <p class="page-lede">What this project is running, and the answers it was generated from.</p>

      <section class="section">
        <h2 class="section-title">Stack</h2>
        <dl class="rows">
          <For each={STACK}>
            {(entry) => {
              return (
                <div class="row">
                  <dt>{entry.name}</dt>
                  <dd>{entry.version}</dd>
                </div>
              );
            }}
          </For>
        </dl>
      </section>

      <section class="section">
        <h2 class="section-title">Your answers</h2>
        <dl class="rows">
          <For each={ANSWERS}>
            {(entry) => {
              return (
                <div class="row">
                  <dt>{entry.label}</dt>
                  <dd>{entry.value}</dd>
                </div>
              );
            }}
          </For>
        </dl>
        <p class="note">
          Recorded in
          {' '}
          <code>linteljs.config.json</code>
          , which
          {' '}
          <code>sync</code>
          {' '}
          reads.
        </p>
      </section>
    </main>
  );
};
