// packages/create/templates/starter-source/vue/src/components/features/app-header/AppHeader.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';

import { ROUTES } from '@views/routes';

import { styles } from './appHeaderStyles';

interface Props {
  name: string;
}

defineProps<Props>();

const route = useRoute();
</script>

<template>
  <header v-bind="styles.header">
    <p v-bind="styles.starterLabel">
      LintelJS Starter
    </p>
    <p v-bind="styles.brand">
      {{ name }}
    </p>
    <nav
      v-bind="styles.tabs"
      aria-label="Main"
    >
      <!-- vue-router sets aria-current on the active link itself. -->
      <RouterLink
        v-for="entry in ROUTES"
        :key="entry.id"
        v-bind="styles.tab(entry.path === route.path)"
        :to="entry.path"
      >
        {{ entry.label }}
      </RouterLink>
    </nav>
  </header>
</template>

// packages/create/templates/starter-source/react/react-router/src/components/features/app-header/AppHeader.tsx
import { NavLink } from 'react-router';

import { ROUTES } from '@router/router';

import { styles } from './appHeaderStyles';

import type { FC } from 'react';

export interface AppHeaderProps {
  readonly name: string;
}

export const AppHeader: FC<AppHeaderProps> = ({ name }) => {
  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>LintelJS Starter</p>
      <p {...styles.brand}>{name}</p>
      <nav {...styles.tabs} aria-label="Main">
        {ROUTES
          .map(({
            id,
            label,
            path,
          }) => {
            return (
              <NavLink
                key={id}
                to={path}
                end
                className={({ isActive }) => {
                  return styles.tab(isActive).className;
                }}
                style={({ isActive }) => {
                  return styles.tab(isActive).style;
                }}
              >
                {label}
              </NavLink>
            );
          })}
      </nav>
    </header>
  );
};
