// packages/create/templates/starter-source/next/src/components/features/app-header/AppHeader.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

import { PAGES } from '@config/routes';

import { styles } from './appHeaderStyles';

import type { ReactNode } from 'react';

export interface AppHeaderProps {
  readonly name: string;
}

// A client component: `usePathname` marks the current tab, and a server component cannot read it.
export const AppHeader = ({ name }: AppHeaderProps): ReactNode => {
  const pathname = usePathname();

  return (
    <header {...styles.header}>
      <p {...styles.starterLabel}>LintelJS Starter</p>
      <p {...styles.brand}>{name}</p>
      <nav {...styles.tabs} aria-label="Main">
        {PAGES
          .map(({
            id,
            label,
            path,
          }) => {
            return (
              <Link
                key={id}
                {...styles.tab(pathname === path)}
                href={path}
                aria-current={pathname === path ? 'page' : undefined}
              >
                {label}
              </Link>
            );
          })}
      </nav>
    </header>
  );
};

// packages/create/templates/starter-source/svelte/src/components/features/app-header/AppHeader.svelte
<script lang="ts">
  import { page } from '$app/state';

  import { PAGES } from '@config/routes';

  import { styles } from './appHeaderStyles';

  interface Props {
    name: string;
  }

  const { name }: Props = $props();
</script>

<!-- Real links: SvelteKit routes by URL. -->
<header {...styles.header}>
  <p {...styles.starterLabel}>LintelJS Starter</p>
  <p {...styles.brand}>{name}</p>
  <nav {...styles.tabs} aria-label="Main">
    {#each PAGES as entry (entry.id)}
      <a
        {...styles.tab(page.url.pathname === entry.path)}
        href={entry.href}
        aria-current={page.url.pathname === entry.path ? 'page' : undefined}
      >
        {entry.label}
      </a>
    {/each}
  </nav>
</header>
