// packages/create/templates/starter-source/next/i18n/src/components/features/language-select/LanguageSelect.tsx
'use client';

import { useLocale, useTranslations } from 'next-intl';

import { languages } from '@i18n/config';
import { chooseLanguage } from '@i18n/i18n';

import type { ComponentProps, ReactNode } from 'react';

export type LanguageSelectProps = Pick<ComponentProps<'select'>, 'className' | 'style'>;

// Styled by the header that holds it, so every header keeps one visual language.
export const LanguageSelect = (props: LanguageSelectProps): ReactNode => {
  const t = useTranslations();
  const language = useLocale();

  return (
    <select
      {...props}
      aria-label={t('language')}
      value={language}
      onChange={(event) => {
        chooseLanguage(event.target.value);
      }}
    >
      {languages
        .map(({ id, label }) => {
          return (
            <option
              key={id}
              value={id}
              lang={id}
            >
              {label}
            </option>
          );
        })}
    </select>
  );
};

// packages/create/templates/starter-source/solid/i18n/src/components/features/language-select/LanguageSelect.tsx
import { For, type JSX } from 'solid-js';

import {
  chooseLanguage,
  language,
  t,
} from '../../../i18n';
import { languages } from '../../../i18n/config';

export type LanguageSelectProps = Pick<JSX.SelectHTMLAttributes<HTMLSelectElement>, 'class' | 'style'>;

// Styled by the header that holds it, so every header keeps one visual language.
export const LanguageSelect = (props: LanguageSelectProps): JSX.Element => {
  return (
    <select
      {...props}
      aria-label={t('language')}
      value={language()}
      onChange={(event) => {
        chooseLanguage(event.currentTarget.value);
      }}
    >
      <For each={languages}>
        {(option) => {
          return (
            <option value={option.id} lang={option.id}>
              {option.label}
            </option>
          );
        }}
      </For>
    </select>
  );
};
