// packages/create/templates/starter-source/solid/i18n/src/components/features/language-select/LanguageSelect.tsx
import { For, type JSX } from 'solid-js';

import {
  chooseLanguage,
  language,
  t,
} from '../../../i18n';
import { languages } from '../../../i18n/config';

export type LanguageSelectProps = Pick<JSX.SelectHTMLAttributes<HTMLSelectElement>, 'class' | 'style'>;

// Styled by the header that holds it, so every header keeps one visual language.
export const LanguageSelect = (props: LanguageSelectProps): JSX.Element => {
  return (
    <select
      {...props}
      aria-label={t('language')}
      value={language()}
      onChange={(event) => {
        chooseLanguage(event.currentTarget.value);
      }}
    >
      <For each={languages}>
        {(option) => {
          return (
            <option value={option.id} lang={option.id}>
              {option.label}
            </option>
          );
        }}
      </For>
    </select>
  );
};

// packages/create/templates/starter-source/svelte/i18n/src/components/features/language-select/LanguageSelect.svelte
<script lang="ts">
  import {
    chooseLanguage,
    locale,
    m,
  } from '@i18n';
  import { languages } from '@i18n/config';

  import type { HTMLSelectAttributes } from 'svelte/elements';

  const attributes: HTMLSelectAttributes = $props();
</script>

<!-- Styled by the header that holds it, so every header keeps one visual language. -->
<select
  {...attributes}
  value={$locale}
  aria-label={m.language()}
  onchange={(event) => {
    chooseLanguage(event.currentTarget.value);
  }}
>
  {#each languages as option (option.id)}
    <!-- Spread: a bare `value` compiles to a branch only a re-render reaches. -->
    <option {...{ value: option.id, lang: option.id }}>{option.label}</option>
  {/each}
</select>
