// packages/create/templates/starter-source/svelte/i18n/src/routes/about/+page.svelte
<script lang="ts">
  import {
    CHECK,
    GATE,
    SYNC,
  } from '@config/linteljs';
  import { STANDARD_PATHS } from '@config/standard';

  import { m } from '@i18n/i18n';

  import CodeText from '@ui/code-text/CodeText.svelte';
</script>

<main class="page">
  <h1 class="page-title">{m.about()}</h1>
  <p class="page-lede">{m.aboutLede()}</p>

  <section class="section">
    <h2 class="section-title">{m.aboutGate()}</h2>
    <ul class="rows">
      {#each GATE as leg (leg.command)}
        <li class="row">
          <code class="key">{leg.command}</code>
          <span class="value">{leg.runs}</span>
        </li>
      {/each}
    </ul>
    <p class="note">
      <CodeText text={m.aboutCheck({ command: CHECK })} />
    </p>
  </section>

  <section class="section">
    <h2 class="section-title">{m.aboutStandard()}</h2>
    <dl class="rows">
      {#each STANDARD_PATHS as entry (entry.path)}
        <div class="row">
          <dt><code>{entry.path}</code></dt>
          <dd>{m[entry.holds]()}</dd>
        </div>
      {/each}
    </dl>
  </section>

  <section class="section">
    <h2 class="section-title">{m.aboutCurrent()}</h2>
    <p class="note">
      <CodeText text={m.aboutSync({ command: SYNC })} />
    </p>
  </section>
</main>

// packages/create/templates/starter-source/react-native/i18n/src/app/about.tsx
import { useTranslation } from 'react-i18next';
import {
  ScrollView,
  Text,
  View,
} from 'react-native';

import { GATE } from '@config/linteljs';
import { STANDARD_PATHS } from '@config/standard';
import { useStarterStyles } from '@styles/starter';

import type { ReactNode } from 'react';

const AboutScreen = (): ReactNode => {
  const { t } = useTranslation();
  const { layout, text } = useStarterStyles();

  return (
    <ScrollView style={layout.screen} role="main">
      <Text style={text.pageTitle}>{t('about')}</Text>
      <Text style={text.lede}>{t('aboutLede')}</Text>

      <Text style={text.sectionTitle}>{t('aboutGate')}</Text>
      {GATE
        .map((leg) => {
          return (
            <View key={leg.command} style={layout.row}>
              <Text style={text.key}>{leg.command}</Text>
              <Text style={text.value}>{leg.runs}</Text>
            </View>
          );
        })}

      <Text style={text.sectionTitle}>{t('aboutStandard')}</Text>
      {STANDARD_PATHS
        .map((entry) => {
          return (
            <View key={entry.path} style={layout.row}>
              <Text style={text.key}>{entry.path}</Text>
              <Text style={text.value}>{t(entry.holds)}</Text>
            </View>
          );
        })}
    </ScrollView>
  );
};

export default AboutScreen;
