// packages/create/templates/starter-source/solid/with-store-i18n/src/pages/home/HomePage.tsx
import { CHECK } from '@config/linteljs';

import { useCounter } from '@store/counter/counterStore';
import { t } from '@i18n';

import { Button, Mark } from '@ui';
import { CodeText } from '@ui/code-text/CodeText';

import type { JSX } from 'solid-js';

export interface HomePageProps {
  readonly name: string;
}

export const HomePage = (props: HomePageProps): JSX.Element => {
  const counter = useCounter();

  return (
    <main class="hero">
      <Mark />
      <h1 class="title">{props.name}</h1>
      <p class="lede">{t('homeLedeSolid')}</p>

      {/* State that outlives the page: switch tabs and come back, and the count is still here. */}
      <div class="counter">
        <span class="count" aria-live="polite">{counter.count()}</span>
        <Button onClick={counter.add}>{t('homeAdd')}</Button>
      </div>
      <p class="caption">{t('homeCaption')}</p>

      <p class="hint">
        <CodeText text={t('gateHint', { command: CHECK })} />
      </p>
    </main>
  );
};

// packages/create/templates/starter-source/react/with-store-i18n/src/pages/home/HomePage.tsx
import { Trans, useTranslation } from 'react-i18next';

import { CHECK } from '@config/linteljs';

import { useCounter } from '@store/counter/counterStore';

import { Button, Mark } from '@ui';

import type { FC } from 'react';

export interface HomePageProps {
  readonly name: string;
}

const CODE = { code: <code /> };
const CHECK_VALUES = { command: CHECK };

export const HomePage: FC<HomePageProps> = ({ name }) => {
  const { t } = useTranslation();
  const { count, add } = useCounter();

  return (
    <main className="hero">
      <Mark />
      <h1 className="title">{name}</h1>
      <p className="lede">{t('homeLedeReact')}</p>

      {/* State that outlives the page: switch tabs and come back, and the count is still here. */}
      <div className="counter">
        <span className="count" aria-live="polite">{count}</span>
        <Button onClick={add}>{t('homeAdd')}</Button>
      </div>
      <p className="caption">{t('homeCaption')}</p>

      <p className="hint">
        <Trans
          i18nKey="gateHint"
          values={CHECK_VALUES}
          components={CODE}
        />
      </p>
    </main>
  );
};
