// packages/create/templates/starter-source/solid/tanstack-query/src/lib/providers/DataProvider.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/solid-query';

import type { JSX } from 'solid-js';

export interface DataProviderProps {
  readonly children: JSX.Element;
}

// One client for the application, made once rather than per render.
const client = new QueryClient();

export const DataProvider = (props: DataProviderProps): JSX.Element => {
  return <QueryClientProvider client={client}>{props.children}</QueryClientProvider>;
};

// packages/create/templates/starter-source/react/tanstack-query/src/lib/providers/data/DataProvider.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import type { FC, ReactNode } from 'react';

export interface DataProviderProps {
  readonly children: ReactNode;
}

// One client for the application, made once rather than per render.
const client = new QueryClient();

export const DataProvider: FC<DataProviderProps> = ({ children }) => {
  return <QueryClientProvider client={client}>{children}</QueryClientProvider>;
};
