// packages/create/templates/starter-source/solid/src/components/features/error-boundary/ErrorBoundary.tsx
import { ErrorBoundary as SolidErrorBoundary, type JSX } from 'solid-js';

import { STATUSES } from '../../../config/statuses';
import { ForbiddenError } from '../../../lib/utils/statusUtils';
import { StatusPage } from '../status-page/StatusPage';

export interface ErrorBoundaryProps {
  readonly children: JSX.Element;
}

export const ErrorBoundary = (props: ErrorBoundaryProps): JSX.Element => {
  return (
    <SolidErrorBoundary fallback={(error, reset) => {
      // Trying again cannot grant access.
      if (error instanceof ForbiddenError) {
        return <StatusPage {...STATUSES.forbidden} />;
      }

      return <StatusPage {...STATUSES.serverError} onRetry={reset} />;
    }}
    >
      {props.children}
    </SolidErrorBoundary>
  );
};

// packages/create/templates/starter-source/react/src/components/features/error-boundary/ErrorBoundary.tsx
import { Component, type ReactNode } from 'react';

import { STATUSES } from '../../../config/statuses';
import { ForbiddenError } from '../../../lib/utils/statusUtils';
import { StatusPage } from '../status-page/StatusPage';

export interface ErrorBoundaryProps {
  readonly children: ReactNode;
}

interface ErrorBoundaryState {
  readonly failed: boolean;
  readonly forbidden: boolean;
}

// A class: React catches a render error only in `getDerivedStateFromError`, which has no hook.
export class ErrorBoundary extends Component<ErrorBoundaryProps, ErrorBoundaryState> {
  override state: ErrorBoundaryState = {
    failed: false,
    forbidden: false,
  };

  static getDerivedStateFromError(error: unknown): ErrorBoundaryState {
    return {
      failed: true,
      forbidden: error instanceof ForbiddenError,
    };
  }

  override render(): ReactNode {
    // A fragment, so both branches are one type.
    if (!this.state.failed) {
      return <>{this.props.children}</>;
    }

    // Trying again cannot grant access.
    if (this.state.forbidden) {
      return <StatusPage {...STATUSES.forbidden} />;
    }

    return (
      <StatusPage
        {...STATUSES.serverError}
        onRetry={() => {
          this.setState({
            failed: false,
            forbidden: false,
          });
        }}
      />
    );
  }
}
