// packages/create/templates/starter-source/svelte/src/routes/contact/+page.svelte
<script lang="ts">
  import Button from '@ui/button/Button.svelte';
  import TextInput from '@ui/text-input/TextInput.svelte';

  import { useContactForm } from './useContactForm';

  const form = useContactForm();
</script>

<main class="page">
  <h1 class="page-title">Contact</h1>
  <p class="page-lede">Two fields, validated on blur. Nothing is sent anywhere.</p>

  {#if form.sent}
    <p class="sent" role="status">Thanks. Nothing was sent, this is a starter.</p>
  {:else}
    <form novalidate onsubmit={form.onSubmit}>
      <TextInput {...form.fields.email} />
      <TextInput {...form.fields.message} />
      <Button type="submit" disabled={!form.canSubmit}>Send</Button>
    </form>
  {/if}
</main>

// packages/create/templates/starter-source/next/src/app/contact/page.tsx
'use client';

import { Button, TextInput } from '@ui';

import { useContactForm } from './useContactForm';

import type { ReactNode } from 'react';

// A client component: a form is state.
const ContactPage = (): ReactNode => {
  const {
    fields,
    sent,
    submitting,
    canSubmit,
    onSubmit,
  } = useContactForm();

  return (
    <main className="page">
      <h1 className="page-title">Contact</h1>
      <p className="page-lede">Two fields, validated on blur. Nothing is sent anywhere.</p>

      {sent
        ? (
            <p className="sent" role="status">Thanks. Nothing was sent, this is a starter.</p>
          )
        : (
            <form noValidate onSubmit={onSubmit}>
              <TextInput {...fields.email} />
              <TextInput {...fields.message} />
              <Button type="submit" disabled={!canSubmit || submitting}>Send</Button>
            </form>
          )}
    </main>
  );
};

export default ContactPage;
