// packages/create/templates/starter-source/angular/i18n/src/components/ui/code-text/code-text.ts
import {
  Component,
  computed,
  input,
} from '@angular/core';

// A translation marks each command `<code>`: split here, so no message is rendered as HTML.
@Component({
  selector: 'app-code-text',
  templateUrl: './code-text.html',
})
export class CodeText {
  readonly text = input.required<string>();

  protected readonly parts = computed(() => {
    const text = this.text();

    return text.split(/<\/?code>/u);
  });
}

// packages/create/templates/starter-source/solid/i18n/src/components/ui/code-text/CodeText.tsx
import { Index, type JSX } from 'solid-js';

export interface CodeTextProps {
  readonly text: string;
}

// A translation marks each command `<code>`: split here, so no message is rendered as HTML.
export const CodeText = (props: CodeTextProps): JSX.Element => {
  return (
    <span>
      <Index each={props.text.split(/<\/?code>/u)}>
        {(part, index) => {
          return index % 2 === 1 ? <code>{part()}</code> : <>{part()}</>;
        }}
      </Index>
    </span>
  );
};
