// packages/create/templates/starter-source/solid/src/lib/providers/DataProvider.tsx
import type { JSX } from 'solid-js';

export interface DataProviderProps {
  readonly children: JSX.Element;
}

/*
 * The slot a data layer fills. With none there is nothing to provide, so this passes its children through
 * and TanStack Query replaces this file with its own client.
 */
export const DataProvider = (props: DataProviderProps): JSX.Element => {
  // Wrapped rather than returned: reading `props.children` outside JSX reads it once and never again.
  return <>{props.children}</>;
};

// packages/create/templates/starter-source/next/src/lib/providers/DataProvider.tsx
'use client';

import type { FC, ReactNode } from 'react';

export interface DataProviderProps {
  readonly children: ReactNode;
}

/*
 * The slot a data layer fills. With none, and with RTK Query (whose provider is the Redux one beside it), there is
 * nothing to provide, so this passes its children through.
 *
 * The directive is what makes this the client boundary: the layout above it is a server component, and everything
 * under it inherits the browser.
 */
export const DataProvider: FC<DataProviderProps> = ({ children }) => {
  return children;
};
