// packages/create/templates/starter-source/next/i18n/src/app/contact/page.tsx
'use client';

import { useTranslations } from 'next-intl';

import { Button, TextInput } from '@ui';

import { useContactForm } from './useContactForm';

import type { ReactNode } from 'react';

// A client component: a form is state.
const ContactPage = (): ReactNode => {
  const t = useTranslations();
  const {
    fields,
    sent,
    submitting,
    canSubmit,
    onSubmit,
  } = useContactForm((key) => {
    return t(key);
  });

  return (
    <main className="page">
      <h1 className="page-title">{t('contact')}</h1>
      <p className="page-lede">{t('contactLede')}</p>

      {sent
        ? (
            <p className="sent" role="status">{t('contactSent')}</p>
          )
        : (
            <form noValidate onSubmit={onSubmit}>
              <TextInput {...fields.email} />
              <TextInput {...fields.message} />
              <Button type="submit" disabled={!canSubmit || submitting}>{t('contactSend')}</Button>
            </form>
          )}
    </main>
  );
};

export default ContactPage;

// packages/create/templates/starter-source/svelte/i18n/src/routes/contact/+page.svelte
<script lang="ts">
  import { m } from '@i18n';

  import Button from '@ui/button/Button.svelte';
  import TextInput from '@ui/text-input/TextInput.svelte';

  import { useContactForm } from './use-contact-form/useContactForm';

  const form = useContactForm((key) => {
    return m[key]();
  });
</script>

<main class="page">
  <h1 class="page-title">{m.contact()}</h1>
  <p class="page-lede">{m.contactLede()}</p>

  {#if form.sent}
    <p class="sent" role="status">{m.contactSent()}</p>
  {:else}
    <form novalidate onsubmit={form.onSubmit}>
      <TextInput {...form.fields.email} />
      <TextInput {...form.fields.message} />
      <Button type="submit" disabled={!form.canSubmit}>{m.contactSend()}</Button>
    </form>
  {/if}
</main>
